/**
 * Pixel-art sprites for the weighted cursor's hover personalities.
 *
 * Each sprite is a 16x16 grid of palette keys ("." = transparent), rendered
 * as merged SVG rects. Elements opt in via `data-cursor="<name>"`; the
 * cursor morphs into the sprite while hovering (see WeightedCursor).
 */

export interface PixelSprite {
  palette: Record<string, string>;
  /** 16 rows of 16 chars; each char indexes `palette`, "." is transparent. */
  grid: string[];
}

export interface SpriteRect {
  x: number;
  y: number;
  w: number;
  fill: string;
}

/** Run-length merge each row into horizontal rects (fewer DOM nodes). */
export function spriteRects(sprite: PixelSprite): SpriteRect[] {
  const rects: SpriteRect[] = [];
  sprite.grid.forEach((row, y) => {
    let x = 0;
    while (x < row.length) {
      const ch = row[x];
      if (ch === ".") {
        x++;
        continue;
      }
      let w = 1;
      while (x + w < row.length && row[x + w] === ch) w++;
      rects.push({ x, y, w, fill: sprite.palette[ch] });
      x += w;
    }
  });
  return rects;
}

/* Sprite data generated by codex (gpt-5.6 Sol), hand-tuned where needed. */
export const SPRITES: Record<string, PixelSprite> = {
  pen: {
    palette: { "O": "#1d1d21", "B": "#315f9b", "D": "#243f6b", "H": "#6fa8dc", "G": "#d49a33", "Y": "#ffd166" },
    grid: [
      "................",
      ".............OO.",
      "............OBHO",
      "...........OBBDO",
      "..........OBHBDO",
      ".........OBBBDO.",
      "........OBHBDO..",
      ".......OBBBDO...",
      "......OOHBDO....",
      ".....OGOBDO.....",
      "...OOGGGOO......",
      "..OGGGGGO.......",
      ".OGGYGGO........",
      "OGGGGO..........",
      ".OGGO...........",
      "..OO............",
    ],
  },
  rifle: {
    palette: { "O": "#1d1d21", "W": "#8f4e2b", "L": "#c47a3b", "S": "#59301f", "M": "#3a4047", "H": "#7b8792" },
    grid: [
      "................",
      "................",
      "................",
      "..........OOOOOO",
      "..OOOOOOOOOMMMMO",
      ".OWWWLOMMHMMMOO.",
      "OWWWWOMMMMMMO...",
      ".OOOOOOOOOOOO...",
      "....OWO.OMMO....",
      "....OWO.OMMMO...",
      ".....OO.OMMMO...",
      ".........OMMMO..",
      "..........OMMMO.",
      "...........OMMO.",
      "............OO..",
      "................",
    ],
  },
  terminal: {
    palette: { "O": "#1d1d21", "C": "#a89f86", "D": "#716b61", "S": "#17251f", "G": "#43d66f", "H": "#a0ff8f" },
    grid: [
      "................",
      "...OOOOOOOOOO...",
      "..OCCCCCCCCCCO..",
      "..OCOOOOOOOOCO..",
      "..OCOSSSSSSOCO..",
      "..OCOSGSSSHOCO..",
      "..OCOSSGSSHOCO..",
      "..OCOSGSSSHOCO..",
      "..OCOSSSSSSOCO..",
      "..OCOOOOOOOOCO..",
      "..OCCCCDDDDCCO..",
      "...OOOOOOOOOO...",
      "......OCCO......",
      ".....OCDDO......",
      "....OOOOOOOO....",
      "................",
    ],
  },
  phone: {
    palette: { "O": "#1d1d21", "S": "#8e98a8", "K": "#303746", "B": "#3b9ee8", "P": "#ee568d", "Y": "#ffd447" },
    grid: [
      ".....OOOOOO.....",
      "....OSSSSSSO....",
      "....OSOOOOSO....",
      "....OKBBBBKO....",
      "....OBBBBBBO....",
      "....OBBOBBBO....",
      "....OBOOBOPO....",
      "....OBBOBBYO....",
      "....OBBBBBBO....",
      "....OBPPYYBO....",
      "....OBBBBBBO....",
      "....OKKKKKKO....",
      "....OSOOOOSO....",
      "....OSSSSSSO....",
      "....OSSOOSSO....",
      ".....OOOOOO.....",
    ],
  },
  robot: {
    palette: { "O": "#1d1d21", "S": "#8c9aa5", "D": "#56636d", "C": "#28d9e8", "H": "#a4faff", "A": "#f0a23c" },
    grid: [
      ".......OO.......",
      "......OAAO......",
      ".......OO.......",
      "....OOOOOOOO....",
      "..OOSSSSSSSSOO..",
      ".OSSSSSSSSDDDDO.",
      ".OSOOOSSSOOODDO.",
      ".OSOCCSSSOCCODO.",
      ".OSOCHSSSOCHODO.",
      ".OSOOOSSSOOODDO.",
      ".OSSSSSSSSSDDDO.",
      ".OSSSOOOOSSDDDO.",
      ".OSSSOCCOSSDDDO.",
      ".OOSSOOOOSSDDOO.",
      "...OOOOOOOOOO...",
      "................",
    ],
  },
  wheat: {
    palette: { "O": "#1d1d21", "W": "#d89b32", "H": "#ffd35a", "S": "#a76528", "G": "#4f9b45", "D": "#2f6f3e" },
    grid: [
      ".......OO.......",
      "......OWHO......",
      ".....OWSWO......",
      "......OWO.......",
      "...OO.OWWO.OO...",
      "..OWO..OGO..OWO.",
      ".OWHWO.OGO.OWHWO",
      "..OWO..OGO..OWO.",
      "...OO..OGO..OO..",
      "....OOOOGOOOO...",
      ".......OGO......",
      "...OO..OGO......",
      "..OGDOOOGO......",
      ".OGGDO.OGO......",
      "..OOOO.OGO......",
      ".......OO.......",
    ],
  },
  pc: {
    palette: { "O": "#1d1d21", "C": "#89939d", "D": "#555f69", "S": "#202933", "R": "#35d8d1", "P": "#d85bd5" },
    grid: [
      "................",
      ".OOOOOOOOO......",
      "OCCCCCCCCCO.....",
      "OCOSSSSSSCO.OOO.",
      "OCOSRRSSSCOOCCCO",
      "OCOSSRSSSCOOCDCO",
      "OCOSSSSPPCOOCCCO",
      "OCOSSSSSSCOOCDCO",
      "OCOOOOOOOCOOCRCO",
      "OCCCCCCCCCOOCCCO",
      ".OOOOOOOOO.OCDCO",
      "....OCCO...OCCCO",
      "...OCDDO...OCCCO",
      "..OOOOOOOO.OCCCO",
      "...........OOROO",
      "...........OOOOO",
    ],
  },
  earth: {
    palette: { "O": "#1d1d21", "B": "#287fc1", "H": "#68bce8", "G": "#4f9b55", "T": "#c4934a", "W": "#f2f1e8" },
    grid: [
      ".....OOOOOO.....",
      "...OOHHBBBBOO...",
      "..OHBBBBBBBBBO..",
      ".OHBBGGGBBBBBBO.",
      ".OBBGGTGGBWWBBO.",
      "OBBBGGTTGBBBBBBO",
      "OBWBBGTTTGBBBBBO",
      "OBBBBBGGGGBBBBBO",
      "OBBGGBBBBBGTBBBO",
      "OBGGGTBBBBBGTTBO",
      ".OGTTTGBBWWBBO..",
      ".OBGTGBBBBBBBO..",
      "..OBBBBBBBBBBO..",
      "...OOBBBBBBOO...",
      ".....OOOOOO.....",
      "................",
    ],
  },
  joystick: {
    palette: { "O": "#1d1d21", "R": "#d94444", "H": "#ff7a55", "K": "#383842", "B": "#416aa3", "Y": "#f1c742" },
    grid: [
      "......OOOO......",
      "....OORRRROO....",
      "...ORRHHHRRRO...",
      "...ORRRRRRRRO...",
      "....OORRRROO....",
      "......OKO.......",
      "......OKO.......",
      "......OKO.......",
      ".....OOKOO......",
      "..OOOOOOOOOOOO..",
      ".OBBBBBBBBBBBBO.",
      "OBBBBBOYOBOROBBO",
      "OBBBBBBBBBBKKKKO",
      ".OBBBBBBBBKKKKO.",
      "..OOOOOOOOOOOO..",
      "................",
    ],
  },
};
